apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service
  labels:
    app: config-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-service
          image: ghcr.io/anandkrish4204/config-service
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9001
          lifecycle:
            preStop:
              exec:
                command: ["sh","-c","sleep 5"]